version: "3.8"

services:

    rabbit:
        hostname: 'rabbit'
        image: rabbitmq:3.8.5-management
        ports:
            - '5672:5672'
            - '15672:15672'
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 30s
            retries: 3
        volumes:
            - ~/volume/rabbit-data:/var/lib/rabbitmq/
            - ~/volume/rabbit-logs:/var/log/rabbitmq/
        networks:
            - net

    persistence:
        build: back-end
        environment:
            - NODECLASS=persistence
            - RABBITURL=rabbit
        volumes:
            - ~/volume/persistence:/persistence/
        networks:
            - net

    master:
        build: back-end
        ports:
            - '8000:8000'
        environment:
            - NODECLASS=master
            - RABBITURL=rabbit
        volumes:
            - ~/volume/predict_files:/app/predict_files/
            - ~/volume/task_files:/app/task_files/
        networks:
            - net

    worker:
        build: back-end
        environment:
            - NODECLASS=worker
            - RABBITURL=rabbit
        volumes:
            - ~/volume/predict_files:/app/predict_files/
            - ~/volume/task_files:/app/task_files/
        networks:
            - net

    caddy:
        build: caddy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ~/volume/front:/usr/share/caddy
        networks:
            - net

    front:
        build: front-end
        volumes:
            - ~/volume/front:/app/dist
        networks:
            - net

networks:
    net:
        driver: bridge