# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
      
#       - name: Import SSH key
#         run: |
#           mkdir -p ~/.ssh/
#           echo "$APROMORE_SERVER_KEY" > ../apromore-server-key.pem
#           sudo chmod 600 apromore-server-key.pem
#         shell: bash
#         env:
#           APROMORE_SERVER_KEY: ${{secrets.APROMORE_SERVER_KEY}}
      
#       - name: Import known hosts
#         run: ssh-keyscan -H "$APROMORE_SERVER_HOST" > ~/.ssh/known_hosts
#         shell: bash
#         env:
#           APROMORE_SERVER_HOST: ${{secrets.APROMORE_SERVER_HOST}}
      
      - name: SSH to Apromore server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.APROMORE_SERVER_HOST}}
          username: ubuntu
          key: ${{secrets.APROMORE_SERVER_KEY}}
          script: |
            cd PredictiveMonitoring
            git remote set-url origin git@github.com:SWEN90013-2021-BP/PredictiveMonitoring.git
            git pull origin dev
            cd src
            docker-compose up --build
